### PR TITLE
add my-cool-app.com bot ToS and privacy policy placeholder

### PR DESCRIPTION
**Pull request by vcokltfre**
image

### CODE REVIEW

**Comment by vcokltfre** [comment]
To clarify: this url is actually owned by discord and does redirect to discord.com, it's not just a placeholder

**Comment by advaith1** [comment]
Discord doesn't own it, someone else bought it

**Comment by e5510** [comment]
I don’t think it is owned by discordimage

**Comment by vcokltfre** [comment]
ah my bad, seems my info was wrong

**Pull request closed without merging**
