### PR TITLE
Update shortlinks.txt

### PR DESCRIPTION
**Pull request by DzikStar**

### CODE REVIEW

**Comment by Lulalaby** [comment]
That tweet which is referenced is not public anymore.
Not sure if we should add that

**Comment by Lulalaby** [comment]
@Techy whatcha think

**Comment by DzikStar** [comment]
Even if this tweet is not public, I think this shortlink should be published. 

Isn't the purpose of this repository sometimes to collect data (literally all data?). 
You still can read comments uder this tweet and view tweet if account owner will allow you to follow this account (https://twitter.com/tahukann)

**Comment by Lulalaby** [comment]
Fair ig. Not feeling well

**Pull request merged**
