### PR TITLE
Added new user flags and guild feature

### PR DESCRIPTION
**Pull request by Lulalaby**
Source for user `COLLABORATOR` flags: https://github.com/Discord-Datamining/Discord-Datamining/commit/bc3df38401a040ee80a42df33909e929d9820620#commitcomment-101842128

Source for the other user flags: https://flags.lewisakura.moe

Source for guild feature: image

### CODE REVIEW

**Comment by Lulalaby** [comment]
@Techy one merge please

**Review by MDCYT — CHANGES_REQUESTED** [review]
It looks good, but why don't they add the rest of the missing flags, in https://flags.lewisakura.moe/ there are some that are not here.

image

**Comment by Lulalaby** [comment]
uh ya, i can do that

**Comment by Lulalaby** [comment]
i'm going to make food and add it within the next hour

**Comment by Lulalaby** [comment]
Done

**Comment by Lulalaby** [comment]
I've additionally added a row with info about whether the flag is documented (in the api documentation)

**Review by MDCYT — APPROVED** [review]

**Comment by Lulalaby** [comment]
@Techy if that's too much added here, i'm gonna revert it. just lmk

**Comment by Techy** [comment]
@Lulalaby Looks good!

**Pull request merged**
